/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * utama.java
 *
 * Created on Nov 28, 2010, 1:41:41 PM
 */

package form;

/**
 *
 * @author Trie
 */
import logic.EWSGenerator;
import logic.PSIGenerator;
import logic.RunExternalCommand;
import javax.swing.SwingUtilities.*;
import javax.swing.filechooser.FileFilter;
import java.io.*;
import java.util.Properties;
import javax.swing.*;
import javax.swing.JOptionPane;


public class KontrolGui extends javax.swing.JFrame {

EWSGenerator ews;
PSIGenerator psi;
String   WarningCode="", TotalWarning="", Message="", Region1="", Region2="", Region3="", TotalRegion="";
String ServerDesc="", ServerID="";
String[] hasilvideo = new String[6];
String[] hasilbitrate = new String[6];
int[] hasilPIDvideo = new int[6];
int[] hasilPIDaudio = new int[6];
int ini = 0;
String filename,filedir;
String textsum, combine;
int sumbitrate, sumbitrateews;
File file;
String folderUser;
String userName,networkName,CountryID;
int PIDAudio,PIDVideo;

    /** Creates new form utama */
public String PROP_FILE = ".konfigurasi.trie";

    public KontrolGui() {
        ews = new EWSGenerator();
        psi = new PSIGenerator();
        initComponents();

                       

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        ButtonSend = new javax.swing.JButton();
        ButtonNoEws = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jMuxing = new javax.swing.JButton();
        jLokasiFile = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jBrowseFile = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jJumlahVideo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jbitrate = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPIDAudio = new javax.swing.JTextField();
        jPIDVideo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jBoardType = new javax.swing.JComboBox();
        jModulation = new javax.swing.JComboBox();
        jIntervalGuard = new javax.swing.JComboBox();
        jConvolutionalRate = new javax.swing.JComboBox();
        jFrequency = new javax.swing.JComboBox();
        jPlayDTV = new javax.swing.JButton();
        jStopDTV = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jPort = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jIPServer = new javax.swing.JTextField();
        jPortServer = new javax.swing.JTextField();
        jPlayIPTV = new javax.swing.JButton();
        jStopIPTV = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuClose = new javax.swing.JMenu();
        jMenuOpen = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuExit = new javax.swing.JMenuItem();
        jSetting = new javax.swing.JMenu();
        jConfigure = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SOFTWARE CONTROL D-EWS v0.1");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(196, 92, 83));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Badan Pengkajian dan Penerapan Teknologi");

        jLabel26.setFont(new java.awt.Font("Tahoma", 2, 10));
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("create @2011");

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoBpptMini.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel26))
                .addGap(224, 224, 224))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(jLabel26))
                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.setEnabled(false);

        jPanel5.setBackground(new java.awt.Color(216, 249, 253));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Server  Descriptor");

        jLabel2.setText("Warning Code");

        jLabel3.setText("Warning Message");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BPPT", "BMKG", "BVMBG", "BNPB" }));
        jComboBox1.setSelectedIndex(1);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cadangan", "Tsunami", "Gempa Bumi", "Banjir", "Banjir Lahar", "Banjir Bandang", "Asap Kebakaran", "Awan Panas", "EWS Testing" }));
        jComboBox2.setSelectedIndex(1);

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("-");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel5.setText("Region Code");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Nanggroe Aceh Darussalam", "Sumatera Utara", "Riau", "Kapulauan Riau", "Sumatera Barat", "Jambi", "Bengkulu", "Sumatera Selatan", "Bangka Belitung", "Lampung", "Banten", "DKI Jarkarta", "Jawa Barat", "Jawa Tengah", "DI Yogyakarta", "Jawa Timur", "Bali", "Nusa Tenggara Barat", "Nusa Tenggara Timur", "Kalimantan Barat", "Kalimantan Tengah", "Kalimantan Timur", "Kalimantan Selatan", "Sulawesi Utara", "Gorontalo", "Sulawesi Barat", "Sulawesi Tengah", "Sulawesi Selatan", "Sulawesi Tenggara", "Maluku Utara", "Maluku", "Papua Barat", "Papua" }));
        jComboBox3.setSelectedIndex(1);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Nanggroe Aceh Darussalam", "Sumatera Utara", "Riau", "Kapulauan Riau", "Sumatera Barat", "Jambi", "Bengkulu", "Sumatera Selatan", "Bangka Belitung", "Lampung", "Banten", "DKI Jarkarta", "Jawa Barat", "Jawa Tengah", "DI Yogyakarta", "Jawa Timur", "Bali", "Nusa Tenggara Barat", "Nusa Tenggara Timur", "Kalimantan Barat", "Kalimantan Tengah", "Kalimantan Timur", "Kalimantan Selatan", "Sulawesi Utara", "Gorontalo", "Sulawesi Barat", "Sulawesi Tengah", "Sulawesi Selatan", "Sulawesi Tenggara", "Maluku Utara", "Maluku", "Papua Barat", "Papua" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Nanggroe Aceh Darussalam", "Sumatera Utara", "Riau", "Kapulauan Riau", "Sumatera Barat", "Jambi", "Bengkulu", "Sumatera Selatan", "Bangka Belitung", "Lampung", "Banten", "DKI Jarkarta", "Jawa Barat", "Jawa Tengah", "DI Yogyakarta", "Jawa Timur", "Bali", "Nusa Tenggara Barat", "Nusa Tenggara Timur", "Kalimantan Barat", "Kalimantan Tengah", "Kalimantan Timur", "Kalimantan Selatan", "Sulawesi Utara", "Gorontalo", "Sulawesi Barat", "Sulawesi Tengah", "Sulawesi Selatan", "Sulawesi Tenggara", "Maluku Utara", "Maluku", "Papua Barat", "Papua" }));

        ButtonSend.setText("Send");
        ButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSendActionPerformed(evt);
            }
        });

        ButtonNoEws.setText("Clear");
        ButtonNoEws.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNoEwsActionPerformed(evt);
            }
        });

        jLabel9.setText("max. 50 caracter");

        jLabel10.setText("Region 1");

        jLabel11.setText("Region 2");

        jLabel12.setText("Region 3");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(ButtonNoEws)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonSend)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(7, 7, 7)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(7, 7, 7)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonSend)
                            .addComponent(ButtonNoEws))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("EWS Config", jPanel1);

        jPanel9.setBackground(new java.awt.Color(216, 249, 253));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMuxing.setText("Muxing");
        jMuxing.setEnabled(false);
        jMuxing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMuxingActionPerformed(evt);
            }
        });

        jLokasiFile.setEditable(false);

        jLabel19.setText("Video TS");

        jBrowseFile.setText("Browse");
        jBrowseFile.setEnabled(false);
        jBrowseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrowseFileActionPerformed(evt);
            }
        });

        jLabel20.setText("Jumlah Video");

        jJumlahVideo.setEditable(false);

        jLabel21.setText("Biterate");

        jbitrate.setEditable(false);

        jLabel22.setText("PID");

        jLabel23.setText("Audio:");

        jLabel24.setText("Video:");

        jPIDAudio.setEditable(false);

        jPIDVideo.setEditable(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(78, 78, 78)
                        .addComponent(jLokasiFile, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel23)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbitrate)
                            .addComponent(jJumlahVideo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jPIDAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel24)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPIDVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBrowseFile)
                    .addComponent(jMuxing))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBrowseFile)
                    .addComponent(jLabel19)
                    .addComponent(jLokasiFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(jJumlahVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jbitrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jPIDAudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jPIDVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMuxing))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Content", jPanel3);

        jPanel6.setBackground(new java.awt.Color(216, 249, 253));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel6.setText("DVB-T");

        jLabel7.setText("Board Type");

        jLabel8.setText("Modulation");

        jLabel13.setText("Interval guard");

        jLabel14.setText("Convolutional rate");

        jLabel15.setText("Frequency");

        jBoardType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "100", "102", "107", "110", "140", "115" }));
        jBoardType.setSelectedIndex(3);
        jBoardType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jBoardTypeItemStateChanged(evt);
            }
        });

        jModulation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "QPSK", "QAM16", "QAM64" }));
        jModulation.setSelectedIndex(1);

        jIntervalGuard.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1/4", "1/8", "1/16", "1/32" }));

        jConvolutionalRate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1/2", "2/3", "3/4", "5/6", "7/8" }));

        jFrequency.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "474", "482", "490", "498", "506", "514", "522", "530", "538", "546", "554", "562", "570", "578", "586", "594", "602", "610", "618", "626", "634", "642", "650", "658", "666", "674", "682", "690", "698", "706", "714", "722", "730", "738", "746", "754", "762", "770", "778", "786", "794", "802", "810", "818", "826", "834", "842", "850", "858" }));
        jFrequency.setSelectedIndex(23);

        jPlayDTV.setText("Play");
        jPlayDTV.setEnabled(false);
        jPlayDTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlayDTVActionPerformed(evt);
            }
        });

        jStopDTV.setText("Stop");
        jStopDTV.setEnabled(false);
        jStopDTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStopDTVActionPerformed(evt);
            }
        });

        jLabel25.setText("Port Output");

        jPort.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel6)
                .addContainerGap(179, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jStopDTV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPlayDTV))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPort, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jModulation, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jFrequency, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jConvolutionalRate, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jIntervalGuard, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBoardType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(68, 68, 68))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBoardType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jModulation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jIntervalGuard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jConvolutionalRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPlayDTV)
                    .addComponent(jStopDTV))
                .addGap(23, 23, 23))
        );

        jPanel7.setBackground(new java.awt.Color(216, 249, 253));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel16.setText("IP-TV");

        jLabel17.setText("IP Server");

        jLabel18.setText("Port Server");

        jIPServer.setText("224.0.1.2");

        jPortServer.setText("1234");

        jPlayIPTV.setText("Play");
        jPlayIPTV.setEnabled(false);
        jPlayIPTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlayIPTVActionPerformed(evt);
            }
        });

        jStopIPTV.setText("Stop");
        jStopIPTV.setEnabled(false);
        jStopIPTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStopIPTVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addGap(27, 27, 27))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jStopIPTV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPortServer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPlayIPTV, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jIPServer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(39, 39, 39)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jIPServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jPortServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPlayIPTV)
                    .addComponent(jStopIPTV))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Play", jPanel4);

        jMenuClose.setText("File");

        jMenuOpen.setText("Open");
        jMenuClose.add(jMenuOpen);

        jMenuItem1.setText("Close");
        jMenuClose.add(jMenuItem1);

        jMenuExit.setText("Exit");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        jMenuClose.add(jMenuExit);

        jMenuBar1.add(jMenuClose);

        jSetting.setText("Setting");

        jConfigure.setText("Configure");
        jConfigure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConfigureActionPerformed(evt);
            }
        });
        jSetting.add(jConfigure);

        jMenuBar1.add(jSetting);

        jMenuHelp.setText("Help");
        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bootOn(){

        //Lihat user yang sedang aktif pada ubuntu
        BufferedReader stdInput = null;
        String cmdfolder = "whoami";

        try{
            Process p = Runtime.getRuntime().exec(cmdfolder);
            stdInput = new BufferedReader(new InputStreamReader(p.getInputStream()));
            String eachline = null;
            while((eachline = stdInput.readLine()) != null){
                folderUser = "/home/"+eachline+"/";
                System.out.println("User yang aktif adalah: "+eachline);
                System.out.println("Lokasi folder yang aktif adalah: "+folderUser);
                }
            }
        catch(Exception e){
            System.err.println("Ada kesalahan !!!");
            }

        //Buka file properties
        Properties p2 = new Properties();
        p2 = loadProperties(PROP_FILE);
        //Mendapatkan nilai key
        networkName = p2.getProperty("Host Server");
        System.out.println("Nama jaringan yang aktif: "+networkName);
        userName = p2.getProperty("Nama Aplikasi");
        CountryID = p2.getProperty("ID Region");
        //String ServiceName = p2.getProperty("Service Name");
        //System.out.println("Hasil: "+ServiceName);


        //Membuat folder temps jika belum ada
        // triedepok@gmail.com
        String[] cmd = new String[3];
        cmd[0] = "/bin/sh";
        cmd[1] = "-c";
        cmd[2] = "mkdir "+folderUser+"temps;" +
                 "sudo Dta1xxInit start";
        System.out.println("Jalankan program: "+cmd[2]);

        try{
            Process p = Runtime.getRuntime().exec(cmd);
           }
        catch (IOException e) {
            System.out.println("[IOException]. Printing Stack Trace");
            e.printStackTrace();
            System.exit(-1);
           }

    }


    public static Properties loadProperties(String sFile) {
	Properties p = new Properties();
		try {
			FileInputStream in = new FileInputStream(sFile);
			p.load(in);
			System.out.println("File konfigurasi '" + sFile + "' berhasil dibuka");
			in.close();
                    }
		catch (IOException iOException) {
                        new SimpanKonfig().setVisible(true);
                        JOptionPane.showMessageDialog(null, "Lakukan konfigurasi pada menu Setting \nterlebih dahulu!!!","Error",JOptionPane.ERROR_MESSAGE);
                    }
	return p;
}



    private int predictBitrate(String av){
        String predict =  "tspcrmeasure "+av+" 4000000";
        int bitrateAV = 0;
        BufferedReader stdInput = null;
        String cmdpredict =  predict;

        try{
            Process p = Runtime.getRuntime().exec(cmdpredict);
            stdInput = new BufferedReader(new InputStreamReader(p.getInputStream()));
            }
        catch(Exception e){
            System.err.println("Ada kesalahan dalam menghitung bitrate");
            }

        try{
            String eachline = null;
            String hasil="";
            while((eachline = stdInput.readLine()) != null){
                hasil = eachline;
                //System.out.println(hasil);
                eachline = stdInput.readLine();
                }
            String[] bitrate = hasil.split(" ");
            double bitrate2 = Double.parseDouble(bitrate[bitrate.length-1]);
            bitrateAV = (int)bitrate2;

            }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Gagal membuat bitrate","Error",JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            }
        return bitrateAV;
    }


    private void predictPID(String av){

        //Tri Miyarno
        String[] hasilPID = new String[2];
        String[] hasilService = new String[2];
        String predict =  "tsinfo "+av;
        BufferedReader stdInput = null;
        String cmdpid = predict;

        try{
            Process p = Runtime.getRuntime().exec(cmdpid);
            stdInput = new BufferedReader(new InputStreamReader(p.getInputStream()));
            String eachline = null;

            int i=0;
            while((eachline = stdInput.readLine()) != null){

                    if (!eachline.equals("")){

                            if (eachline.substring(4, 7).equals("PID")){
                                //System.out.println(eachline);
                                hasilPID[i] = eachline.substring(15, 18).trim();
                                hasilService[i] = eachline.substring(40, 42).trim();
                                System.out.println(hasilPID[i]);
                                System.out.println(hasilService[i]);
                                i = i+1;

                                }
                        }
                }

            System.out.println("Prediksi PID berhasil dilakukan");
            //PIDAudio = Integer.valueOf(hasilPID[0]).intValue();
            //PIDVideo = Integer.valueOf(hasilPID[1]).intValue();
            //System.out.println(Integer.valueOf(hasilService[0]).intValue());
            if (Integer.valueOf(hasilService[0]).intValue() == 2 || Integer.valueOf(hasilService[0]).intValue() == 3) {
                PIDAudio = Integer.valueOf(hasilPID[0]).intValue();
                PIDVideo = Integer.valueOf(hasilPID[1]).intValue();
                 }

            else {
                PIDVideo = Integer.valueOf(hasilPID[0]).intValue();
                PIDAudio = Integer.valueOf(hasilPID[1]).intValue();
                }

            
            }
        catch(Exception e){
            System.err.println("Ada kesalahan !!!");
            }

    }


    private void createPSI(){
        String s = "";
        String namaFile = folderUser+"temps/psiconfig.py";
        file = new File(namaFile);
        try{
            int[] serviceID = {1,2,3,4,5,6,7};
            String[] serviceName = {"Channel-1","Channel-2","Channel-3","Channel-4","Channel-5","Channel-6","Channel-EWS"};
            int[] valuePMTID = {4096,1032,1033,1034,1035,1036,1037};
            String[] providerName = {"Prog-1","Prog-2","Prog-3","Prog-4","Prog-5","Prog-6","Prog-EWS"};
            FileWriter fw = new FileWriter(namaFile);
            s = psi.generatePSI(ini,serviceID, serviceName, valuePMTID, networkName, providerName,folderUser,hasilPIDvideo, hasilPIDaudio);
            fw.write(s);
            // Close file writer
            fw.close();

            // Beri hak akses untuk eksekusi dan jalankan
            RunExternalCommand tri = new RunExternalCommand();
            tri.cmd[0] = "/bin/sh";
            tri.cmd[1] = "-c";
            tri.cmd[2] = "chmod +x "+folderUser+"temps/psiconfig.py;" +
                         folderUser+"temps/psiconfig.py";
            tri.runcommand();
            System.out.println("Program berhasil dijalankan");
            }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Gagal membuat file PSI","Error",JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            }
        

        

    }

    private void createEWS(){
        String p = "";
        String namaFile = folderUser+"temps/ewsconfig.py";
        file = new File(namaFile);

        // Seleksi untuk jumlah region becana
        //triedepok@gmail.com
        String[] Region = null;
        if (Region1.equals("0")){
            JOptionPane.showMessageDialog(null, "Tidak ada lokasi bencana","Pesan",JOptionPane.ERROR_MESSAGE);
            Region = new String[] {Region1};
            //jTabbedPane1.setEnabled(false);
            }
            else if (Region2.equals("0")){
                Region = new String[] {Region1};
                }
                else if (Region3.equals("0")){
                    Region = new String[] {Region1,Region2};
                    }
        else{
            Region = new String[] {Region1,Region2,Region3};
            }
        

        try{

            String[] WarningDisc = {"Cadangan","Tsunami","Gempa Bumi","Banjir","Banjir Lahar","Banjir Bandang","Asap Kebakaran","Awan Panas","EWS Testing"};
            String[] RegionDisc1 = {"NAD","SUMUT","RIAU","KEPRI","SUMBAR","JAMBI","BENGKULU","SUMSEL","BABEL","LAMPUNG"};
            String[] RegionDisc2 = {"BANTEN","DKI JAKARTA","JABAR","JATENG","DI YOGYAKARTA","JATIM","BALI","NTB","NTT","KALBAR"};
            String[] RegionDisc3 = {"KALTENG","KALTIM","KALSEL","SULUT","GORONTALO","SULBAR","SULTENG","SULSEL","SULTRA","MALUT"};
            String[] RegionDisc4 = {"MALUKU","PAPUA BARAT","PAPUA"};
            FileWriter fw = new FileWriter(namaFile);
            p = ews.generateEWS(ServerID, ServerDesc, CountryID, WarningCode, WarningDisc, Message, TotalRegion, Region, folderUser, RegionDisc1, RegionDisc2, RegionDisc3, RegionDisc4);
            fw.write(p);
            // Close file writer
            fw.close();

            //Jalankan pyton untuk PSI
            RunExternalCommand tri = new RunExternalCommand();
            tri.cmd[0] = "/bin/sh";
            tri.cmd[1] = "-c";
            tri.cmd[2] = "chmod +x "+folderUser+"temps/ewsconfig.py;" +
                         folderUser+"temps/ewsconfig.py";
            tri.runcommand();
            System.out.println("Program berhasil dijalankan");
            }

        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Gagal membuat file EWS","Error",JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            }

        
    }



    @SuppressWarnings("empty-statement")
    private void ButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSendActionPerformed
        // Triedepok@gmail.com
        ServerID = String.valueOf(jComboBox1.getSelectedIndex());
        ServerDesc = (String) jComboBox1.getSelectedItem();
        WarningCode = String.valueOf(jComboBox2.getSelectedIndex());
        TotalWarning = String.valueOf(jComboBox2.getItemCount());
        //Jika selain angka desimal dirubah menjadi hexa
            if (WarningCode.equals("8")){
                WarningCode = "0xFF" ;
              }

        Message =  jTextArea1.getText();
        Region1 = String.valueOf(jComboBox3.getSelectedIndex());
        Region2 = String.valueOf(jComboBox4.getSelectedIndex());
        Region3 = String.valueOf(jComboBox5.getSelectedIndex());
        TotalRegion = String.valueOf(jComboBox3.getItemCount()-1);
        if (!jTextArea1.getText().isEmpty())
            {
            //Jalankan pembuatan file PSI untuk EWS
            createEWS();
            ButtonSend.setEnabled(false);
            jComboBox1.setEnabled(false);
            jComboBox2.setEnabled(false);
            jComboBox3.setEnabled(false);
            jComboBox4.setEnabled(false);
            jComboBox5.setEnabled(false);
            jTextArea1.setEnabled(false);
            jTabbedPane1.setEnabled(true);
            jBrowseFile.setEnabled(true);
            }
        else
            {
            JOptionPane.showMessageDialog(null,"Text harus di isi...","Error",JOptionPane.ERROR_MESSAGE);
            }
        
        
    }//GEN-LAST:event_ButtonSendActionPerformed

    private void ButtonNoEwsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNoEwsActionPerformed
        BufferedReader stdInput = null;
        String cmd = "pwd";

        try{
            Process pa = Runtime.getRuntime().exec(cmd);
            stdInput = new BufferedReader(new InputStreamReader(pa.getInputStream()));
            String eachline = null;
            while((eachline = stdInput.readLine()) != null){
                System.out.println("Folder aktif: "+eachline);
                }
            }
        catch(Exception e){
            System.err.println("Ada kesalahan !!!");
            }

        //jBrowseFile.setEnabled(true);
        //jTabbedPane1.setSelectedIndex(1);

        jTextArea1.setText("-");
        ButtonSend.setEnabled(true);
        jTabbedPane1.setEnabled(false);
        jComboBox1.setEnabled(true);
        jComboBox2.setEnabled(true);
        jComboBox3.setEnabled(true);
        jComboBox4.setEnabled(true);
        jComboBox5.setEnabled(true);
        jTextArea1.setEnabled(true);

    }//GEN-LAST:event_ButtonNoEwsActionPerformed

    private void jStopDTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStopDTVActionPerformed

        //Keluarkan proses tsudpsend dari system
        String cmdkill = "killall -TERM DtPlay &" +
                         "killall -TERM sh";

        try{
            Process p = Runtime.getRuntime().exec(cmdkill);
            }
        catch (IOException e) {
            System.out.println("[IOException]. Printing Stack Trace");
            e.printStackTrace();
            System.exit(-1);
            }

        jPlayDTV.setEnabled(true);
        jStopDTV.setEnabled(false);
        jPlayIPTV.setEnabled(true);
        jBoardType.setEnabled(true);
        jPort.setEnabled(true);
        jModulation.setEnabled(true);
        jIntervalGuard.setEnabled(true);
        jConvolutionalRate.setEnabled(true);
        jFrequency.setEnabled(true);
    }//GEN-LAST:event_jStopDTVActionPerformed

    private void jPlayDTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlayDTVActionPerformed

        //Melakukan konfigurasi untuk DTA Card --- triedepok#gmail.com
            combine = "DtPlay "+folderUser+"temps/fifostamp.ts -t "+jBoardType.getItemAt(jBoardType.getSelectedIndex())
                +" -mt OFDM"
                +" -r "+sumbitrate
                +" -i "+jPort.getItemAt(jPort.getSelectedIndex())
                +" -mC "+jModulation.getItemAt(jModulation.getSelectedIndex())
                +" -mG "+jIntervalGuard.getItemAt(jIntervalGuard.getSelectedIndex())
                +" -mc "+jConvolutionalRate.getItemAt(jConvolutionalRate.getSelectedIndex())
                +" -mf "+jFrequency.getItemAt(jFrequency.getSelectedIndex());

            String[] cmd = new String[3];
            cmd[0] = "/bin/sh";
            cmd[1] = "-c";
            cmd[2] = textsum+combine;
            System.out.println("Proses muxing: "+cmd[2]);

            try{
                Process p = Runtime.getRuntime().exec(cmd);
                }
            catch (IOException e) {
                System.out.println("[IOException]. Printing Stack Trace");
                e.printStackTrace();
                System.exit(-1);
                }

        jStopDTV.setEnabled(true);
        jPlayDTV.setEnabled(false);
        jPlayIPTV.setEnabled(false);
        jTabbedPane1.setSelectedIndex(0);
        jBoardType.setEnabled(false);
        jPort.setEnabled(false);
        jModulation.setEnabled(false);
        jIntervalGuard.setEnabled(false);
        jConvolutionalRate.setEnabled(false);
        jFrequency.setEnabled(false);

    }//GEN-LAST:event_jPlayDTVActionPerformed

    private void jPlayIPTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlayIPTVActionPerformed

        if(!jIPServer.getText().equals("") && !jPortServer.getText().equals("")){
            // Jalankan dan konfigurasi untuk TSUDPSEND
            combine = "tsudpsend "+folderUser+"temps/fifomuxed.ts "+jIPServer.getText()+" "+jPortServer.getText()+" "+sumbitrate ;

            String[] cmd = new String[3];
            cmd[0] = "/bin/sh";
            cmd[1] = "-c";
            cmd[2] = textsum+combine;
            System.out.println("Proses muxing: "+cmd[2]);

            try{
                Process p = Runtime.getRuntime().exec(cmd);
                }
            catch (IOException e) {
                System.out.println("[IOException]. Printing Stack Trace");
                e.printStackTrace();
                System.exit(-1);
                }

            jStopIPTV.setEnabled(true);
            jPlayIPTV.setEnabled(false);
            jPlayDTV.setEnabled(false);
            //jTabbedPane1.setEnabled(true);
            jTabbedPane1.setSelectedIndex(0);
            jIPServer.setEnabled(false);
            jPortServer.setEnabled(false);
        }

    }//GEN-LAST:event_jPlayIPTVActionPerformed

    private void jStopIPTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStopIPTVActionPerformed

        //Keluarkan proses tsudpsend dari system
        String cmdkill = "killall -TERM tsudpsend &" +
                         "killall -TERM sh";

        try{
            Process p = Runtime.getRuntime().exec(cmdkill);
            }
        catch (IOException e) {
            System.out.println("[IOException]. Printing Stack Trace");
            e.printStackTrace();
            System.exit(-1);
            }
        
        
        jStopIPTV.setEnabled(false);
        jPlayIPTV.setEnabled(true);
        jPlayDTV.setEnabled(true);
        jIPServer.setEnabled(true);
        jPortServer.setEnabled(true);
    }//GEN-LAST:event_jStopIPTVActionPerformed

    private void jMuxingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMuxingActionPerformed

        //buat table PSI
        createPSI();

        //Proses Muxing sementara
        //triedepok@gmail.com
        int psibit = 1504;
        int bitews = 88;
        int bit1=0,bit2=0;
        //Menghitung jumlah birate keseluruhan
        //triedepok@gmail.com
        for(int i = 1 ; i <= (ini) ; ++i){
            bit1 = bit1+Integer.valueOf(psibit).intValue();
            bit2 = bit2+Integer.valueOf(hasilbitrate[i-1]).intValue();
            }
        sumbitrateews = (bitews*9);
        sumbitrate = (bit1 + bit2 + sumbitrateews);

        //Menjalankan proses muxing dengan opencaster
        textsum =   "mkfifo "+folderUser+"temps/fifomuxed.ts;" +
                    "mkfifo "+folderUser+"temps/fifostamp.ts;" +
                    "mkfifo "+folderUser+"temps/fifoloop.ts;" +
                    "tscbrmuxer " +
                    "b:"+bitews+" "+folderUser+"temps/mptspmtews.ts "+
                    "b:"+bitews+" "+folderUser+"temps/ewsit.ts "+
                    "b:"+bitews+" "+folderUser+"temps/ewsmsg.ts "+
                    "b:"+bitews+" "+folderUser+"temps/ewstsrct.ts "+
                    "b:"+bitews+" "+folderUser+"temps/ewswct.ts "+
                    "b:"+bitews+" "+folderUser+"temps/ewsrct1.ts "+
                    "b:"+bitews+" "+folderUser+"temps/ewsrct2.ts "+
                    "b:"+bitews+" "+folderUser+"temps/ewsrct3.ts "+
                    "b:"+bitews+" "+folderUser+"temps/ewsrct4.ts "+
                    lopingvideo(ini,hasilbitrate,hasilvideo,psibit) +
                    "b:"+psibit+" "+folderUser+"temps/mptssdt.ts "+
                    "b:"+psibit+" "+folderUser+"temps/mptsnit.ts "+
                    "b:"+psibit+" "+folderUser+"temps/mptspat.ts "+
                    "> "+folderUser+"temps/fifomuxed.ts &" +
                    "tsloop "+folderUser+"temps/fifomuxed.ts > "+folderUser+"temps/fifoloop.ts &" +
                    "tsstamp "+folderUser+"temps/fifoloop.ts "+sumbitrate+" > "+folderUser+"temps/fifostamp.ts &";

        System.out.println("Total hasil bitrate: "+sumbitrate);
        jPlayIPTV.setEnabled(true);
        jPlayDTV.setEnabled(true);
        jMuxing.setEnabled(false);
        jBrowseFile.setEnabled(false);
        //jTabbedPane1.setEnabled(false);
        jTabbedPane1.setSelectedIndex(2);

    }//GEN-LAST:event_jMuxingActionPerformed

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed

        this.dispose();

        //Jalankan pengapusan file temp
        String[] cmd = new String[3];
                 cmd[0] = "/bin/sh";
                 cmd[1] = "-c";
                 cmd[2] = "rm -r "+folderUser+"temps &" +
                          "killall -TERM DtPlay &" +
                          "killall -TERM tsudpsend &" +
                          "killall -TERM sh &" +
                          "sudo Dta1xxInit stop";
        System.out.println("Jalankan program : "+cmd[2]);

        try{
            Process p = Runtime.getRuntime().exec(cmd);
            }
        catch (IOException e) {
            System.out.println("[IOException]. Printing Stack Trace");
            e.printStackTrace();
            System.exit(-1);
            }
        
    }//GEN-LAST:event_jMenuExitActionPerformed

    private void jBrowseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrowseFileActionPerformed
 
        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setFileFilter(new FileFilter() {
            public boolean accept(File f) {
                return f.getName().toLowerCase().endsWith(".ts")
                || f.isDirectory();
            }

            public String getDescription() {
            return "TS Files";
            }
        });

        int returnVal = fileChooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION){
            String filepath = fileChooser.getSelectedFile().getPath();
            jLokasiFile.setText(filepath);
            filename = fileChooser.getSelectedFile().getName();
            filedir = filepath.substring(0,(filepath.length()-filename.length()-1));
            }

     //Hitung jumlah video dengan array
        if (ini > 5 ){
            JOptionPane.showMessageDialog(null, "Maaf hanya diperbolehkan sampai 6 video","Error",JOptionPane.ERROR_MESSAGE);
            }
            else if(jLokasiFile.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Maaf harus ada file TS","Error",JOptionPane.ERROR_MESSAGE);
                jTabbedPane1.setEnabled(false);
                getToolkit().beep();
                }

        else{
            hasilvideo[ini] = jLokasiFile.getText();
            System.out.println(hasilvideo[ini]);
            jJumlahVideo.setText(String.valueOf(ini+1)+" TS");
            int bitrate = predictBitrate(jLokasiFile.getText());
            hasilbitrate[ini] = (String.valueOf(bitrate));
            predictPID(jLokasiFile.getText());
            hasilPIDvideo[ini] = PIDVideo;
            hasilPIDaudio[ini] = PIDAudio;
            System.out.println("#Tri Miyarno\n#Hasil PID sebagai berikut");
            System.out.println("PID Audio: "+Integer.toHexString(PIDAudio));
            jPIDAudio.setText("0x"+Integer.toHexString(PIDAudio));
            System.out.println("PID Video: "+Integer.toHexString(PIDVideo));
            jPIDVideo.setText("0x"+Integer.toHexString(PIDVideo));
            System.out.println("Hasil bitrate video: "+hasilbitrate[ini]);
            jbitrate.setText(String.valueOf(hasilbitrate[ini]));
            ini = ini+1;
            
            jMuxing.setEnabled(true);
            }

    }//GEN-LAST:event_jBrowseFileActionPerformed

    private void jConfigureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConfigureActionPerformed

        new SimpanKonfig().setVisible(true);
        //this.dispose();
        
    }//GEN-LAST:event_jConfigureActionPerformed


    //Dijalankan ketika form di load
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        bootOn();
        
    }//GEN-LAST:event_formWindowActivated

    private void jBoardTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jBoardTypeItemStateChanged
        // TODO add your handling code here:
        if (jBoardType.getItemAt(jBoardType.getSelectedIndex()) =="110" ||
            jBoardType.getItemAt(jBoardType.getSelectedIndex()) =="100" ||
            jBoardType.getItemAt(jBoardType.getSelectedIndex()) =="140" ||
            jBoardType.getItemAt(jBoardType.getSelectedIndex()) =="107" ||
            jBoardType.getItemAt(jBoardType.getSelectedIndex()) =="102"){
            jPort.setSelectedIndex(0);
            jPort.setEnabled(false);
        }

        if (jBoardType.getItemAt(jBoardType.getSelectedIndex()) =="115"){
            jPort.setSelectedIndex(1);
            jPort.setEnabled(true);
        }
    }//GEN-LAST:event_jBoardTypeItemStateChanged


    private String lopingvideo(int ini, String[] hasilbitrate, String[] hasilvideo, int psibit) {

        String hasilengkap = "";
        for(int i = 1 ; i <= (ini) ; ++i){
	    hasilengkap += "b:"+hasilbitrate[i-1]+" "+hasilvideo[i-1]+" "+
                           "b:"+psibit+" "+folderUser+"temps/mptspmt"+(i)+".ts ";
            }
            return hasilengkap;
    }
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new KontrolGui().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonNoEws;
    private javax.swing.JButton ButtonSend;
    private javax.swing.JComboBox jBoardType;
    private javax.swing.JButton jBrowseFile;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JMenuItem jConfigure;
    private javax.swing.JComboBox jConvolutionalRate;
    private javax.swing.JComboBox jFrequency;
    private javax.swing.JTextField jIPServer;
    private javax.swing.JComboBox jIntervalGuard;
    private javax.swing.JTextField jJumlahVideo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLokasiFile;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuClose;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuOpen;
    private javax.swing.JComboBox jModulation;
    private javax.swing.JButton jMuxing;
    private javax.swing.JTextField jPIDAudio;
    private javax.swing.JTextField jPIDVideo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton jPlayDTV;
    private javax.swing.JButton jPlayIPTV;
    private javax.swing.JComboBox jPort;
    private javax.swing.JTextField jPortServer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu jSetting;
    private javax.swing.JButton jStopDTV;
    private javax.swing.JButton jStopIPTV;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jbitrate;
    // End of variables declaration//GEN-END:variables

    
}
