/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SimpanKonfig.java
 *
 * Created on Dec 27, 2010, 8:49:59 AM
 */

package form;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author trie
 */
public class SimpanKonfig extends javax.swing.JFrame {

    /** Creates new form SimpanKonfig */
    String IDRegion;


    public String PROP_FILE = ".konfigurasi.trie";

    public SimpanKonfig() {
        initComponents();

        Properties p2 = new Properties();
        p2 = loadProperties(PROP_FILE);
        //Mendapatkan nilai key
        jUserName.setText(p2.getProperty("Nama Aplikasi"));
        jNetName.setText(p2.getProperty("Host Server"));

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jUserName = new javax.swing.JTextField();
        jNetName = new javax.swing.JTextField();
        btnSimpanKonfigurasi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(243, 206, 174));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel1.setText("Konfigirasi System");

        jLabel2.setText("User Name");

        jLabel3.setText("Network Name");

        btnSimpanKonfigurasi.setText("Simpan");
        btnSimpanKonfigurasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanKonfigurasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jUserName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(jNetName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnSimpanKonfigurasi)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnSimpanKonfigurasi)
                    .addComponent(jNetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanKonfigurasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanKonfigurasiActionPerformed
        // TODO add your handling code here:

        if (!jUserName.getText().isEmpty() && !jNetName.getText().isEmpty())
        {

            try {
		/** Menyimpan file properties ke file @param Properties p Object Properties* @param String sFile String path file tujuan*/
		Properties p = new Properties();
		//Menetapkan key dan value draft
                p.setProperty("Nama Aplikasi", jUserName.getText());
		p.setProperty("Host Server", jNetName.getText());
                p.setProperty("ID Region", "62");
                p.setProperty("Service Name", "Channel-1,Channel-2,Channel-3,Channel-4,Channel-5,Channel-6,Channel-EWS");
                p.setProperty("Provider Name", "Prog-1,Prog-2,Prog-3,Prog-4,Prog-5,Prog-6,Prog-EWS");
                p.setProperty("Warning Disaster", "Cadangan,Tsunami,Gempa Bumi,Banjir,Banjir Lahar,Banjir Bandang,Asap Kebakaran,Awan Panas,EWS Testing");
		saveProperties(p, PROP_FILE);
		}
            catch (IOException ex) {
		Logger.getLogger(SimpanKonfig.class.getName()).log(Level.SEVERE, null, ex);
		JOptionPane.showMessageDialog(null, ex.getMessage());
                }

        dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Data harus di isi...","Error",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSimpanKonfigurasiActionPerformed

    public static Properties loadProperties(String sFile) {
	Properties p = new Properties();
		try {
			FileInputStream in = new FileInputStream(sFile);
			p.load(in);
			System.out.println("File konfigurasi '" + sFile + "' berhasil dibuka");
			in.close();
		} 
		catch (IOException iOException) {
                        // Trie
                        //JOptionPane.showMessageDialog(null, "Lakukan konfigurasi pada menu Setting!!!","Error",JOptionPane.ERROR_MESSAGE);
		}
		return p;
}


public static void saveProperties(Properties p, String sFile) throws IOException{FileOutputStream out = null;
	try {
		out = new FileOutputStream(sFile);
		p.store(out, "Data konfigurasi untuk Software Control D-EWS\ntriedepok@gmail.com\nTri Miyarno");
		JOptionPane.showMessageDialog(null, "File konfigurasi berhasil disimpan");
		} 
	catch (FileNotFoundException ex) {
		Logger.getLogger(SimpanKonfig.class.getName()).log(Level.SEVERE, null, ex);
		JOptionPane.showMessageDialog(null, ex.getMessage());
		} 
	finally {
		try {
			out.close();
			} 
		catch (IOException ex) {Logger.getLogger(SimpanKonfig.class.getName()).log(Level.SEVERE, null, ex);
		JOptionPane.showMessageDialog(null, ex.getMessage());
		}
	}
}



    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpanKonfig().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpanKonfigurasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jNetName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jUserName;
    // End of variables declaration//GEN-END:variables

}
